# @package _group_
lr: 0.001
num_epochs: 1001
batch_size: 128
min_lr: 0.00001

data_modality: ["image"]
state_dim: 37
img_h: 128
img_w: 128
num_kp: 64
visual_feature_dimension: 64
action_squash: true
use_eye_in_hand: true
no_skip: true
activation: "leaky-relu"
random_affine: true
affine_translate: 0.025
policy_layer_dims: [300, 400]

policy_type: "normal_subgoal"
