# @package _group_
lr: 0.001
num_epochs: 1001
batch_size: 128
min_lr: 0.0001
num_workers: 0

agglomoration:
        K: 5

data_modality: ["image", "proprio"]
use_gripper: true
use_joints: true
state_dim: 37
img_h: 128
img_w: 128
num_kp: 64
visual_feature_dimension: 64
action_squash: true
use_eye_in_hand: true
no_skip: true
activation: "leaky-relu"
random_affine: true
affine_translate: 4
policy_layer_dims: [300, 400]
subtask_id: []


policy_type: "normal_subgoal"

gripper_smoothing: false

use_rnn: false
rnn_hidden_dim: 100
rnn_num_layers: 2
rnn_encoder_mlp_dims: [128, 128]
rnn_loss_reduction: "mean"

run_idx: 0
  
use_changepoint: true
