# @package _group_
batch_size: 100
num_epochs: 1001
img_h: 128
img_w: 128
num_kp: 64
visual_feature_dimension: 64

use_rnn: false
rnn_hidden_dim: 100
rnn_num_layers: 2

id_layer_dims: [200, 200]
embedding_layer_dims: [400, 500]
use_eye_in_hand: true
activation: "relu"

random_affine: false
affine_translate: 0.02

policy_type: "normal_subgoal"

cvae_cfg:
  enable: true
  kl_coeff: 0.01
  latent_dim: 32
