# @package _group_
lr: 1e-4
batch_size: 100
num_epochs: 1001
num_workers: 0
img_h: 128
img_w: 128
num_kp: 64
visual_feature_dimension: 64
use_spatial_softmax: false

use_rnn: false
rnn_hidden_dim: 100
rnn_num_layers: 2

id_layer_dims: [300, 400]
embedding_layer_dims: [300, 400]
use_eye_in_hand: true
activation: "leaky-relu"

random_affine: false
affine_translate: 4

use_cvae: true
separate_id_prediction: false

